# Build all packages required for a new release. At the moment only the ADO extension is packaged. GitHub action is checked in to the repo 

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g typescript
    npm install -g ts-node
    npm install -g mocha
    npm install -g @zeit/ncc
    npm install -g tfx-cli
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
    npm run bundle
  displayName: "Bundle ADO and GitHub extensions"

- script: |
    # Copy APKs
    cp -r $(build.sourcesdirectory)/dist_gh_action $(build.artifactstagingdirectory)/
    cp -r $(build.sourcesdirectory)/*.vsix $(build.artifactstagingdirectory)/
  displayName: 'Copy extensions to artifacts'

- script: |
    PackageVersion=$(node -e "console.log(require('./package.json').version);")
    echo "##vso[task.setVariable variable=PackageVersion;isOutput=true]$(PackageVersion)"
  displayName: Find bundle version

- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: 'SBOM Manifest Generator'
  inputs:
    BuildDropPath: '$(build.artifactstagingdirectory)'
    Verbosity: Information
    PackageName: 'Microsoft Android App Size Diff CI'
    PackageVersion: $(PackageVersion)

- publish: $(build.artifactstagingdirectory)
  artifact: app-size-diff
  displayName: 'Publish artifacts to pipeline'
